# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: KerioTechnologiesInc.KerioControlVPNClient
PackageVersion: 9.4.7290
PackageLocale: en-US
Publisher: Kerio Technologies Inc.
PackageName: Kerio Control VPN Client
License: Freeware
Copyright: © Kerio Technologies s.r.o. All rights reserved.
ShortDescription: Setup of Kerio Control VPN Client
ManifestType: defaultLocale
ManifestVersion: 1.4.0
